### PR TITLE
Smappee - update switches for local support

### PR DESCRIPTION
**Pull request by ciotlosm**
## Note
Could you please test if this is working correctly with remote? I'm still waiting on my credentials. I received today notification that I need to provide more information before I receive those. 

## Description:
Added local switch support

## Checklist:
  - [x] The code change is tested and works locally.

If the code communicates with devices, web services, or third-party tools:
  - [x] Local tests with `tox` run successfully. **Your PR cannot be merged unless tests pass**
  - [x] New dependencies have been added to the `REQUIREMENTS` variable ([example][ex-requir]).
  - [x] New dependencies are only imported inside functions that use them ([example][ex-import]).
  - [x] New dependencies have been added to `requirements_all.txt` by running `script/gen_requirements_all.py`.
  - [x] New files were added to `.coveragerc`.

### CODE REVIEW

**Comment by hmn** [comment]
you need to run script/gen_requirements_all.py and deploy requirements_all.txt as well

**Comment by hmn** [comment]
I might not have time to test it today, but I'll try to find some time tomorrow to test it

**Comment by ciotlosm** [comment]
I've done another lint fix and did a squash on extra commits with just lint fixes. I'll have a complete check of build and lint and coverage here: https://travis-ci.org/ciotlosm/home-assistant/builds/326349042

**Comment by ciotlosm** [comment]
Crazy thing, it seems that you can do:
```
smappee:
    host: 127.0.0.1:1080
```
And you can run your testing through ssh port forwarding

```
ssh -L 1080:192.168.0.10:80 root@homeassistant.local -p 8888
```

Assuming you used port forward to expose 22 on 8888, you can use the above command to get your 192.168.0.10 local Smappee exposed on the current computer (127.0.0.1) on any port (1080 in the above example)

**Comment by ciotlosm** [comment]
I finally received my Smappee client secret and was able to run tests with a full setup. I've attached more fixes.

**Comment by ciotlosm** [comment]
Found a problem when running it more time. Similar to what was reported on the forum. First you get:

```
Update for sensor.smappee_home_solar_today fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7134beb0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app1pub.smappee.net', port=443): Max retries exceeded with url: /dev/v1/servicelocation/27797/consumption?aggregation=3&from=1515361267903&to=1515447667903 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7134beb0>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/smappee.py", line 117, in update
    self._location_id, aggregation=3, delta=1440)
  File "/config/custom_components/smappee.py", line 159, in get_consumption
    end, aggregation)
  File "/config/deps/lib/python3.6/site-packages/smappy/smappy.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/config/deps/lib/python3.6/site-packages/smappy/smappy.py", line 199, in get_consumption
    aggregation=aggregation)
  File "/config/deps/lib/python3.6/site-packages/smappy/smappy.py", line 257, in _get_consumption
    r = requests.get(url, headers=headers, params=params)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='app1pub.smappee.net', port=443): Max retries exceeded with url: /dev/v1/servicelocation/27797/consumption?aggregation=3&from=1515361267903&to=1515447667903 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7134beb0>: Failed to establish a new connection: [Errno -3] Try again',))
```
and then:
```
Tue Jan 09 2018 00:05:53 GMT+0200 (EET)

Update for sensor.smappee_home_power_today fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/smappee.py", line 126, in update
    consumption = data.get('consumptions')[-1]
IndexError: list index out of range
```

**Comment by hmn** [comment]
it looks like rate limiting on the smappee side, but I guess we need to handle it in a nice way

**Comment by ciotlosm** [comment]
yep, we need to add handling to both that rating limit, but also to general communication error (internet going down, smappee servers going down).

I got another error this morning. If you know how to handle it, just let me know what debug logs you want, so I can enable them tonight.

**Comment by hmn** [comment]
I updated the switch to not do updates as the states are not saved in the platform as far as I know

and then I updated the smappee call's to handle any exceptions and return "sane" values where it made sense

but I guess we could rewrite all of the smappy backend calls to run through a generic handler and then handle backend errors in a generic way

**Pull request merged**
